/* Save a structured nx x ny mesh of elements into a GLVis mesh file with the given name. */

void GLVis_PrintGlobalMesh(const char *meshfile, int Nx, int Ny, int nx, int ny, double hx, double hy)
{
	FILE *file;
	int Dim = 2;
	int NumOfVertices = (Nx * nx + 1) * (Ny * ny * 1);
	int NumOfElements = (Nx * nx) * (Ny * ny);

	int i,j;
	double x, y;

	if ((file = fopen(meshfile, "w")) == NULL)
	{
	   printf("Error: can't open the output file %s\n", meshfile);
	   exit(1);
	}

	/*mesh header */
	fprintf(file, "MFEM mesh v1.0\n");
	fprintf(file, "\ndimension\n");
	fprintf(file, "%d\n", Dim);

	/*mesh elements */
	fprintf(file, "\nelements\n");
	fprintf(file, "%d\n", NumOfElements);
	for (j = 0; j < Ny*ny; j++)
	{
	   for (i = 0; i < Nx*nx; i++)
	   {
		fprintf(file, "1 3 %d %d %d %d\n", i + j * (Nx * nx + 1),
		   i + 1 + j * (Nx * nx + 1), i + 1 + ( j+ 1) * (Nx * nx + 1),
		   i + (j + 1) * (Nx * nx + 1)); 
	   }
	}

	/* boundary will be generated by GLVis */
	fprintf(file, "\nboundary\n");
	fprintf(file, "0\n");
	
	/*mesh vertices */
	fprintf(file, "\nvertices\n");
	fprintf(file, "%d\n", NumOfVertices);
	fprintf(file, "%d\n", Dim);
	for (j = 0; j < Ny * ny + 1; j++)
	{
	  for (i = 0; i < Nx * nx + 1; i++)
	  {
		x = i * hx;
		y = j * hx;
		fprintf(file, "%.14e %.14e\n", x , y);\
	  }
	}

	fflush(file);
	fclose(file);
}

	
